import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from "../components/Header"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div >
      <div>
        <title>Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
      <Header />
      </div>
  )
}
